# Generated by Django 2.0.6 on 2018-06-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ptt',
            fields=[
                ('hash', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ID', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100000)),
                ('time', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Querywho',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
